name: JS Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  js-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Webapp dependencies
        run: yarn install
      - name: Run Webapp tests
        run: yarn run test
      - name: Run Webapp lints
        run: yarn lint
      - name: Run Webapp Format check
        run: yarn format:check
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_step: install

          # TODO: delete below after PR is merged
          # since by default it runs `yarn build` against the PR
          # AND against the `main` branch
          # so it will fail in main since the comman is introduced in this pr itself!
          build_script: './node_modules/.bin/webpack --config scripts/webpack/webpack.prod.js'
